theme: jekyll-theme-cayman
author: joy717
domain: joy717.github.io
url: https://joy717.github.io
lang: zh_CN
paginate: 5
paginate_path: "/blog/page:num/"
markdown: CommonMarkGhPages
plugins:
  - jekyll-seo-tag
  - jekyll-readme-index
  - jekyll-paginate
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"