theme: jekyll-theme-cayman
author: joy717
domain: joy717.github.io
url: https://joy717.github.io
lang: zh_CN
permalink: /:categories/:title:output_ext
markdown: CommonMarkGhPages
plugins:
  - jekyll-seo-tag
  - jekyll-readme-index
  - jekyll-paginate
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"